[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[clusters]
localnet = "http://localhost:8899"
# devnet = "https://api.devnet.solana.com"
# testnet = "https://api.testnet.solana.com"
# mainnet = "https://api.mainnet-beta.solana.com"

[programs.localnet]
access_manager = "4fMih2CidrXPeRx77kj3QcuBZwREYtxEbXjURUgadoe1"
dummy_ibc_app = "5E73beFMq9QZvbwPN5i84psh2WcyJ9PgqF4avBaRDgCC"
gmp_counter_app = "GdEUjpVtKvHKStM3Hph6PnLSUMsJXvcVqugubhtQ5QUD"
ics07_tendermint = "HqPcGpVHxNNFfVatjhG78dFVMwjyZixoKPdZSt3d3TdD"
ics26_router = "FRGF7cthWUvDvAHMUARUHFycyUK2VDUtBchmkwrz7hgx"
ics27_gmp = "3W3h4WSE8J9vFzVN8TGFGc9Uchbry3M4MBz4icdSWcFi"
ics27_ift = "Bedm6bv1H5oCzBYZdQtesZTgHeUjLp7XuUmnhiYwXHn5"
mock_ibc_app = "4Fo5RuY7bEPZNz1FjkM9cUkUVc2BVhdYBjDA8P6Tmox1"
mock_light_client = "CSLS3A9jS7JAD8aUe3LRXMYZ1U8Lvxn9usGygVrA2arZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
