[package]
name = "ics26-router"
version.workspace = true
description = "ICS-26 Routing Module for IBC on Solana"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"
keywords = ["cosmos", "ibc", "solana", "router", "anchor"]
categories = ["cryptography", "blockchain"]

[lib]
crate-type = ["cdylib", "lib"]
name = "ics26_router"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "solana-ibc-types/idl-build"]

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
anchor-spl.workspace = true
solana-ibc-types.workspace = true
solana-ibc-constants.workspace = true
solana-ibc-macros.workspace = true
ics25-handler.workspace = true
access-manager = { workspace = true, features = ["cpi"] }
solana-sha256-hasher.workspace = true
solana-keccak-hasher.workspace = true
hex = "0.4"

[build-dependencies]
sha2 = "0.10"


[dev-dependencies]
mollusk-svm.workspace = true
mollusk-svm-bencher.workspace = true
solana-sdk.workspace = true
bincode.workspace = true
mock-ibc-app = { path = "../mock-ibc-app" }
mock-light-client = { path = "../mock-light-client" }
dummy-ibc-app = { path = "../dummy-ibc-app" }

[lints]
workspace = true
