[package]
name        = "sp1-ics07-utils"
description = "sp1 ics07 utils"
version     = { workspace = true }
edition     = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[dependencies]
