[package]
name = "tendermint-light-client-solana"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tendermint = { workspace = true, features = ["rust-crypto"] }
tendermint-light-client-verifier = { workspace = true }
brine-ed25519 = { workspace = true, features = ["std"] }
sha2 = { workspace = true }
solana-program = { version = "2.3", default-features = false }

