[package]
name = "ethereum-utils"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true, default-features = false }
base64 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tree_hash = { workspace = true }
