[package]
name                 = "ibc-eureka-relayer-eth-to-solana"
version.workspace    = true
edition.workspace    = true
repository.workspace = true
license.workspace    = true

[dependencies]
ibc-eureka-relayer-core          = { workspace = true, default-features = false }
ibc-eureka-relayer-lib.workspace = true
ibc-eureka-utils.workspace       = true
ibc-eureka-solidity-types        = { workspace = true, features = ["rpc"] }

serde                = { workspace = true, features = ["derive"] }
serde_json.workspace = true

tonic   = { workspace = true, default-features = true }
anyhow  = { workspace = true, features = ["std"] }
tracing = { workspace = true, default-features = true }

# EVM dependencies
alloy = { workspace = true, features = ["full", "node-bindings"] }

# Solana dependencies
solana-client.workspace             = true
solana-sdk.workspace                = true
solana-transaction-status.workspace = true
bincode.workspace                   = true
sha2.workspace                      = true
anchor-lang.workspace               = true
borsh.workspace                     = true

ibc-proto-eureka.workspace      = true
prost.workspace                 = true
solana-ibc-types                    = { path = "../../../../programs/solana/packages/solana-ibc-types", features = ["light-client"] }
solana-ibc-constants                = { path = "../../../../programs/solana/packages/solana-ibc-constants" }
solana-ibc-proto                    = { path = "../../../../programs/solana/packages/solana-ibc-proto" }

# SPL Token dependencies
spl-token                    = "8.0"
spl-associated-token-account = "7.0"
