[package]
name       = "sp1-ics07-tendermint-utils"
version    = { workspace = true }
edition    = { workspace = true }
repository = { workspace = true }
license    = { workspace = true }

[dependencies]
anyhow                           = { workspace = true, features = ["std"] }
async-trait                      = { workspace = true }
prost                            = { workspace = true }
cosmos-sdk-proto                 = { workspace = true }
tendermint-rpc                   = { workspace = true }
ibc-eureka-solidity-types        = { workspace = true }
tendermint-light-client-verifier = { workspace = true }
ibc-client-tendermint-types      = { workspace = true }
ibc-core-client-types            = { workspace = true }
ibc-core-host-types              = { workspace = true, features = ["std"] }
tendermint                       = { workspace = true }
ibc-core-commitment-types        = { workspace = true }
alloy-network                    = { workspace = true }
alloy-signer-local               = { workspace = true }
