[package]
name        = "tendermint-light-client-membership"
description = "Verify (non)membership program for tendermint-light-client"
version     = { workspace = true }
edition     = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[features]
solana = ["dep:tendermint-light-client-solana"]

[dependencies]
ibc-core-commitment-types     = { workspace = true }
ibc-core-host-types           = { workspace = true }
thiserror                     = { workspace = true }
tendermint-light-client-solana = { workspace = true, optional = true }

[dev-dependencies]
serde                         = { workspace = true, features = ["derive"] }
hex                           = { workspace = true }
serde_json                    = { workspace = true, features = ["std"] }
prost                         = { workspace = true }
ibc-proto                     = { workspace = true }
