[package]
name = "ethereum-light-client"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
ethereum-trie-db = { workspace = true }
ethereum-utils = { workspace = true }

alloy-primitives = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-rpc-types-beacon = { workspace = true }
alloy-rpc-types-engine = { workspace = true }
alloy-trie = { workspace = true }
alloy-serde = { workspace = true }
alloy-rlp = { workspace = true }
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
tree_hash = { workspace = true }
tree_hash_derive = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
serde_with = { workspace = true }

# TODO: From union (might be removed if they are replaced by something more standard). #147
typenum = { workspace = true, features = ["const-generics", "no_std"] }

[dev-dependencies]
milagro_bls = { workspace = true }
base64 = { workspace = true }
ethereum-test-utils = { workspace = true }
