name: pr

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

jobs:
  title-validation:
    runs-on: ubuntu-latest
    steps:
      - name: conventional-commit
        uses: ytanikin/pr-conventional-commits@1.4.2
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","chore","revert","imp","deps"]'
          add_label: 'false'
